In [1]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers.core import Dense, Dropout, Activation, Flatten

In [2]:
# Part 2 - Fitting the CNN to the images

from keras.preprocessing.image import ImageDataGenerator

In [3]:
img_rows = 150
img_cols = 150
epochs = 10
batch_size = 128
num_of_train_samples = 3000
num_of_test_samples = 600

In [4]:
train_datagen = ImageDataGenerator(rescale=1. / 255,
                                   rotation_range=40,
                                   width_shift_range=0.2,
                                   height_shift_range=0.2,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True,
                                   fill_mode='nearest',validation_split=0.3)

test_datagen = ImageDataGenerator(rescale=1. / 255,validation_split=0.3)

In [5]:
training_set = train_datagen.flow_from_directory('Artists_dataset', 
                                                 subset="training",
                                                 target_size=(img_rows, img_cols),
                                                 batch_size=batch_size,
                                                 class_mode='categorical')


test_set = test_datagen.flow_from_directory('Artists_dataset', 
                                            subset="validation",
                                            target_size=(img_rows, img_cols),
                                            batch_size=batch_size,shuffle=False,
                                            class_mode='categorical')


Found 5606 images belonging to 11 classes.
Found 2397 images belonging to 11 classes.


In [6]:
test_set.class_indices

{'Cezanne': 0,
 'Degas': 1,
 'Manet': 2,
 'Matisse': 3,
 'Monet': 4,
 'Morisot': 5,
 'Pissaro': 6,
 'Renoir': 7,
 'Sargent': 8,
 'Sisley': 9,
 'Sorolla': 10}

In [7]:
model = Sequential()
model.add(Conv2D(32, (14, 14), input_shape=(img_rows, img_cols, 3), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (14, 14), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (14, 14), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(11))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

#Train
model.fit(training_set,
                    steps_per_epoch=num_of_train_samples // batch_size,
                    epochs=epochs,
                    validation_data=test_set,
                    validation_steps=num_of_test_samples // batch_size)

Epoch 1/10
23/23 [==============================] - 153s 7s/step - loss: 4.2278 - accuracy: 0.1137 - val_loss: 2.4322 - val_accuracy: 0.0000e+00
Epoch 2/10
23/23 [==============================] - 160s 7s/step - loss: 2.4249 - accuracy: 0.1330 - val_loss: 2.4647 - val_accuracy: 0.0000e+00
Epoch 3/10
23/23 [==============================] - 151s 6s/step - loss: 2.4237 - accuracy: 0.1315 - val_loss: 2.4995 - val_accuracy: 0.0000e+00
Epoch 4/10
23/23 [==============================] - 144s 6s/step - loss: 2.2923 - accuracy: 0.1681 - val_loss: 2.5472 - val_accuracy: 0.0000e+00
Epoch 5/10
23/23 [==============================] - 144s 6s/step - loss: 2.2878 - accuracy: 0.1549 - val_loss: 2.5373 - val_accuracy: 0.0000e+00
Epoch 6/10
23/23 [==============================] - 143s 6s/step - loss: 2.7131 - accuracy: 0.1710 - val_loss: 2.5848 - val_accuracy: 0.0000e+00
Epoch 7/10
23/23 [==============================] - 142s 6s/step - loss: 2.2634 - accuracy: 0.1591 - val_loss: 2.5737 - val_accura

In [9]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
#Confution Matrix and Classification Report
Y_pred = model.predict_generator(test_set, 60)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(test_set.classes, y_pred))
print('Classification Report')
target_names = list(training_set.class_indices.keys())
print(classification_report(test_set.classes, y_pred, target_names=target_names))

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


Confusion Matrix
[[  0   0   0   0 176   0   0   0   0   0   0]
 [  0   0   0   0 187   0   0   0   0   0   0]
 [  0   0   0   0  68   0   0   2   0   0   0]
 [  0   0   0   0 302   0   0   0   0   0   0]
 [  0   0   0   0 410   0   0   0   0   0   0]
 [  0   0   0   0  72   0   0   0   0   0   0]
 [  0   0   0   0 266   0   0   0   0   0   0]
 [  0   0   0   0 421   0   0   2   0   0   0]
 [  0   0   0   0 237   0   0   2   1   0   0]
 [  0   0   0   0 140   0   0   1   0   0   0]
 [  0   0   0   0 109   0   0   1   0   0   0]]
Classification Report
              precision    recall  f1-score   support

     Cezanne       0.00      0.00      0.00       176
       Degas       0.00      0.00      0.00       187
       Manet       0.00      0.00      0.00        70
     Matisse       0.00      0.00      0.00       302
       Monet       0.17      1.00      0.29       410
     Morisot       0.00      0.00      0.00        72
     Pissaro       0.00      0.00      0.00       266
      Reno

C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
